project:
  type: website
  output-dir: _site
  preview:
    port: 4201

resources: 
  - scss/
  - include/
  - js/
  - img/
  - min/
  - .well-known

website:
  title: "Presentation for Regession Monkey"
  repo-url: https://github.com/RyoNakagami/regmonkey-presentation
  site-url: https://ryonakagami.github.io/regmonkey-presentation
  issue-url: https://github.com/RyoNakagami/regmonkey-presentation/issues
  repo-actions: [issue]
  open-graph: true
  page-navigation: true
  google-analytics:
    # tracking-id: "G-EX9H7GRLTH"
    tracking-id: "G-LVL413SV09"
  favicon: img/favicon.ico
  navbar:
    title: Home
    collapse: true
    left: 
      - icon: book
        menu:
         - text: Ryo's Tech Blog
           href: https://ryonakagami.github.io/
           aria-label: blog-general
         - text: regmoneky datascience blog 
           href: https://ryonakagami.github.io/regmonkey-datascience-blog/
           aria-label: blog-ds
         - text: regmonkey statistics blog 
           href: https://ryonakagami.github.io/regmonkey-statistics-blog/
           aria-label: blog-stat
         - text: cmdstanpy for regmonkey
           href: https://ryonakagami.github.io/cmdstan_for_regression_monkey/
           aria-label: regmonkey_cmd
         - text: statistics dojo
           href: https://ryonakagami.github.io/statistics_dojo/
           aria-label: regmonkey_dojo
         - text: OhGoshGit!?!
           href: https://ohgoshgit.github.io/
           aria-label: blog-ogg
    right: 
      - about.qmd
      - icon: github
        href: https://github.com/RyoNakagami/regmonkey-presentation
      - icon: rss
        href: index.xml
    page-footer:
      border: false
      center:
      - text: "© Copyright RyoNak"
      - text: "License"
        href: LICENSE

format:
  html:
    include-in-header: 
      - include/setup_googletagmanager.html
      - include/custom_webfont.html
      - include/mathjax.html
    include-in-body: 
      - include/setup_googletagmanager_body.html
    include-after-body: 
      - include/custom_section.html
    lang: ja_JP.UTF-8
    number-depth: 1
    self-contained: false
    jupyter: python3
    highlight-style: github
    theme: 
      light: 
        - standalone
        - style/light.scss
      dark: 
        - darkly
        - style/dark.scss
    css: style.css
    code-copy: true
    code-fold: true
    code-overflow: wrap
    date-format: "iso"
    mainfont: "Noto Sans JP"
    monofont: monospace
    toc: true
    highlight: arrow
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto

mermaid:
  theme: default
  gantt: true

tbl-cap-location: top
