---
title: "構造化されたストーリーとしてのスライド"
subtitle: "スライド作成方法論 1"
author: "Ryo Nakagami"
date: "2025-05-07"
categories: [方法論]
slide-number: true
resources:
    - sample_data.csv
filters:
  - reveal-auto-agenda
auto-agenda:
  bullets: bullets
# chalkboard: false
# embed-resources: true
---

# スライド作成の基本

## メッセージの全体像を書き起こしてから、スライド作成にかかる

{{< reveal_vspace 1em >}}

::::{.step-container style="height: 90%"}  

:::{.step }

[① メッセージの作成<br>Planning an argument]{.step .active-phase}

:::{.step-label }

[**ゴール**: 伝えたい内容と目的の明確化]{style="font-size: 1.2em;"}

:::{.checkmark}

- メッセージ設計にあたって3Wを明確化
    - **Who**: 誰を対象にしているか？どのような事前知識を持っているのか？
    - **Why**: 相手にどう行動してほしいのか？どんな印象や判断を促したいのか？
    - **What**: どのような情報を伝えたいのか？{{< reveal_vspace 1em >}}
- テーマ・問題・主張・提案など、伝達したいコアメッセージを言語化
:::
:::
:::


:::{.step }

[② ストーリーの骨子の構築<br>Building an outline]{.step .active-phase }

:::{.step-label }

[**ゴール**: スライド全体の設計図の構築]{style="font-size: 1.2em;"}

:::{.checkmark}

- **Comprehend as they read**
    - 読み手が一度最後まで読み終えてから理解できるのではなく、読んでいる途中でその内容を把握していくことが可能な構成{{< reveal_vspace 2.8em >}}
- スライド全体を「読み手との論理的対話（logical dialogue）」として設計
    - メインメッセージを見た読み手の疑問を予測し、先回りして答える構成で、話の道筋を明確にする

:::
:::
:::

:::{.step }

[③ スライド作成・資料化<br>Drafting paragraphs]{.step .active-phase }

:::{.step-label }

[**ゴール**: 具体的な表現・可視化・構成]{style="font-size: 1.2em;"}

:::{.checkmark}
- すべてのスライドがメッセージとストーリーをサポートするように構成{{< reveal_vspace 1.1em >}}
- 1スライド1メッセージ
    - 論点が増えすぎると、一枚のスライドの内容を把握するのに時間がかかる{{< reveal_vspace 1em >}}
- **MMUF**(Main Message UpFront)
    - メインメッセージを先に示すと、後の詳細パートが理解しやすくなる{{< reveal_vspace 1.1em >}}
- スライド内のオブジェクトを、直感的に理解しやすいように配置・整理
:::
:::
::::

:::

## メッセージ作成の３つのキーポイント

[① メッセージの作成]{.topleftbox}

:::::{.keypoints-container style="height: 90%; width: 100%;"}

::::{.keypoints-block style="height: 100%;"}

:::{.no-border-block}

[① 明確な主張(Argument)が存在すること]{.block-header}

:::{.checkmark}
- スライドの目的は「報告」ではなく、意思決定者に必要な情報をわかりやすく伝え、意思決定を促すこと
- 明確な主張にはRAP[^1]が整理されていることが望ましい
    - **R**: Research Question、「何を明らかにしたいのか？」
    - **A**: Answer、問いに対する答え
    - **P**: Positioning Statement、この主張が全体の議論の中でどういう意味を持つか
:::
:::


:::{.no-border-block}

[② 主張が論理的に構造化されていること]{.block-header}

:::{.checkmark}
- 単に情報を並べるのではなく、意思決定者が判断しやすいよう、情報を整理・構造化することが重要
- 結論を先に示し、その根拠を段階的に説明する **descend structure** が効果的
:::
:::


:::{.no-border-block}


[③ 情報が最小限に絞られていること]{.block-header}

:::{.checkmark}
- スライドに過剰な情報が含まれていると、重要なポイントが埋もれてしまい、判断を迷わせてしまう
- オッカムの剃刀: 「十分な説明が得られるなら、余計な要素を加えるべきではない」
- 「情報を最小限に絞る」＝「本質に集中する作業」であり「情報の省略」ではない
:::

:::

::::
:::::

[^1]: [Varanya Chaubey, The Little Book of Research Writing (CreateSpace Independent Publishing Platform, 2018)](https://www.amazon.co.jp/-/en/Varanya-Chaubey/dp/1974673162).


##  見出しと要点でストーリーを設計する

[② ストーリーの骨子の構築]{.topleftbox}


::::{.step-container style="height: 90%"}

:::{.step }

[全体像の分割（Headingsの定義）]{.step .active-phase}

:::{.step-label}

{{< reveal_vspace 0.5em >}}

:::{.checkmark}

- メインメッセージを、いくつかのグループ(**見出し**)に分ける {{< reveal_vspace 1em >}}
- 専門家・一般読者の両方に通じる、明快な見出し配置を設計する
    - 誰にとっても自然な流れは論理の明快さを意味し、ストーリーの説得力を高める
    - 「次に何が来るのだろう？」と迷うことなく、「なるほど、次は当然この話だな」と感じられるような構成が理想

:::

:::


:::

:::{.step }

[Takeaways(要点)の明確化]{.step .active-phase}

:::{.step-label }

{{< reveal_vspace 0.5em >}}

:::{.checkmark}

- 「言いたいこと」を**主語＋動詞**で、具体的かつ明確に表現 {{< reveal_vspace 1em >}}
- シンプルな文で表現
    - 長い文章だと記憶に残らない{{< reveal_vspace 1em >}}
- 要点が、セクション全体の**「だから何？(So what?)」**という問いに明確に答えているかを確認{{< reveal_vspace 1em >}}
- メインメッセージとの関連を連想させるような表現
    - 「XがYを引き起こすことを示している」
    - 「XがYを引き起こすという主要結果を示している」

:::

:::


:::

:::{.step }

[論理的な順序配置]{.step .active-phase}

:::{.step-label }

{{< reveal_vspace 0.5em >}}

:::{.checkmark}
- 見出しや要点は「理解しやすい順」に配置{{< reveal_vspace 2em >}}
- 「聞き手との論理的対話」を意識
    - 話の導入・展開・結論と聞き手の疑問に先回りして答えるような流れを構築
    - 聞き手の事前知識を想定した上でのスムーズな論理構成

:::


:::

:::

::::


## 明確なスライドメッセージのための３つのキーポイント

[③ スライド作成・資料化]{.topleftbox}

::::{.keypoints-container style="height: 90%; width: 100%;"}

::::{.keypoints-block}

:::{.no-border-block}

[① 1スライド1メッセージ]{.block-header}

:::{.checkmark}
- スライドには伝えたい主張や要点をひとつに絞る
- 複数の情報を詰め込まず、聞き手の理解に集中を促す
    - 複数の主張や結論が同時にあると、聞き手が混乱してしまう{{< reveal_vspace 1em >}}
:::
:::

:::{.no-border-block}

[② 間引きの原則]{.block-header}

:::{.checkmark}
- 聞き手が本質に集中できる構成にする
- 背景情報・前提知識は最低限にとどめる
- 伝えたい内容に直接関係しない情報は思い切って省く

:::
:::

:::{.no-border-block}


[③ 重複排除の原則]{.block-header}

:::{.checkmark}
- 同じ情報を複数のスライドや文で繰り返さない
- 繰り返しが必要なときは、目的を持って再提示
:::
:::

::::
:::::

##  1スライドに複数メッセージが入ってしまっている

[③ スライド作成・資料化]{.topleftbox}




:::{.main-message-block}

[人件費の上昇により売上拡大にも関わらず営業利益減少]{#bad-main-message}

:::

:::: {.columns}
::: {.column width="70%" #bad-example}

<div id="bad-example-container" style="width: 100%; height: 15.5em;"></div>

<script>
// a function to set the series names
let setupSeries = function (series, name, color, hoveredColor) {
  series.name(name).stroke("2 #fff 1").fill(color);
  series.hovered().stroke("1 #fff 1").fill(hoveredColor);
};

anychart.onDocumentReady(function () {
        // Sample annual sales data from 2010 to 2020
        let dataSet = anychart.data.set([
          ["2010", 102, 38],
          ["2011", 114, 37],
          ["2012", 119, 38],
          ["2013", 122, 35],
          ["2014", 126, 33],
          ["2015", 131, 32],
          ["2016", 134, 31],
          ["2017", 137, 28],
          ["2018", 138, 26],
          ["2019", 141, 25]
        ]);
        // Create stacked series
        let cost_series = dataSet.mapAs({ x: 0, value: 1 });
        let profit_series = dataSet.mapAs({ x: 0, value: 2 });

        // create a column chart instance
        let chart = anychart.column();

        // stack values on y scale.
        chart.yScale().stackMode('value');

        // store series
        let series;
        series = chart.column(cost_series);
        setupSeries(series, "費用", "#A9A9A9", "#D31804");
        series.labels()
              .enabled(true)
              .format("{%Value}")  // You can also use "{%y}" for the Y value
              .position("center")  // Optional: "inside", "outside", "center"
              .anchor("center")    // Aligns label within bar
              .fontColor("white") // Good contrast inside a colored bar
              .fontSize(20);
        
        series = chart.column(profit_series);
        setupSeries(series, "営業利益", "#0E3666", "#0E3666");
        series.labels()
              .enabled(true)
              .format("{%Value}")  // You can also use "{%y}" for the Y value
              .position("center")  // Optional: "inside", "outside", "center"
              .anchor("center")    // Aligns label within bar
              .fontColor("white") // Good contrast inside a colored bar
              .fontSize(20);

        // Add title and axis labels
        chart.xAxis().title().fontSize(20).fontWeight("bold").fontFamily("Meiryo");
        chart.yAxis().title().fontSize(20).fontWeight("bold").fontFamily("Meiryo");
        // chart.xAxis().title("Year");
        chart.yAxis().title("Sales (in millions)").padding([0, 0, 10, 0]); // Adding the unit to the 
        chart.xAxis().stroke({ color: "black", thickness: 1 });
        chart.yAxis().stroke({ color: "black", thickness: 1 });

        // Enable legend
        // label config
        var label_x = chart.xAxis().labels();
        var label_y = chart.yAxis().labels();
        label_x.fontFamily("Meiryo");
        label_y.fontFamily("Meiryo");
        label_x.fontSize(20);
        label_y.fontSize(20);
        label_x.fontColor("#1a1a1a");
        label_y.fontColor("#1a1a1a");

        // title config
        var title = chart.title();
        title.enabled(true);
        title.fontSize(22);
        title.fontColor("black");
        title.fontWeight(200);
        title.text("売上と営業利益額の推移(2010~2019年)");
        
        chart.legend(true);

        // Set container and draw
        chart.container("bad-example-container");
        chart.draw();
      });
</script>


<div id="bad-data-table" style="width: 100%;"></div>

<script>
  let FILE_PATH='sample_data.csv'

  // Function to transpose the table data
  function transposeData(data) {
    const transposed = data[0].map((_, colIndex) => data.map(row => row[colIndex]));
    return transposed;
  }
  
  function createTableFromCSV(data) {
    const table = document.createElement("table");
    table.style.borderCollapse = "collapse";
    table.style.width = "100%";
    table.style.fontSize = "0.6em";

    data.forEach((row, rowIndex) => {
      const tr = document.createElement("tr");

      // Apply 'last-row' class to the last row
      if (rowIndex === data.length - 1) {
        tr.classList.add("last-row");
      }

      row.forEach(cell => {
        const cellEl = rowIndex === 0
          ? document.createElement("th")
          : document.createElement("td");
        cellEl.textContent = cell;
        cellEl.style.border = "1px solid #ccc";
        cellEl.style.padding = "8px";
        cellEl.style.textAlign = "center";
        if (rowIndex === 0) cellEl.style.backgroundColor = "#f0f0f0";
        tr.appendChild(cellEl);
      });
      table.appendChild(tr);
    });

    return table;
  }

  document.addEventListener("DOMContentLoaded", function () {
    Papa.parse(FILE_PATH, {
      download: true,
      complete: function (results) {
        const transposedData = transposeData(results.data); // Transpose data
        const container = document.getElementById("bad-data-table");
        container.appendChild(createTableFromCSV(transposedData));
      }
    });
  });
</script>

:::
::: {.column width="30%"}

:::{.message-box style="font-size:0.7em; margin-left:3em;" #tip1}

１つのスライドに２つのメッセージが含まれてしまっている

- 売上上昇にもかかわらず営業利益が減少
- 営業利益減少の主要因は人件費の増加

:::

{{< reveal_vspace 3em >}}

:::{.message-box style="font-size:0.7em; margin-left:3em;" #tip2}

「2010年から10年間売上増大したにもかかわらず営業利益が減少」がメインメッセージのとき、
2011~2018年の数値は本筋に対して過剰な情報

:::

{{< reveal_vspace 4.1em >}}

:::{.message-box style="font-size:0.7em; margin-left:3em;" #tip3}

- 図と表が並列に表示されていることで、どちらに注目すべきかが不明瞭
- 特定の行や列が強調されておらず、全体が等価に見えてしまい，何が重要情報なのかわからない

:::


:::
::::


[]{.leaderline start="#bad-main-message"  end="#tip1"
    color="#575757" end-socket="left" size="3" 
    path="grid"}   

[]{.leaderline start="#bad-example"  end="#tip2"
    path="grid" 
    start-border-style="color:#575757; x: 10%; y:54%; width:87%; height:5%"
    color="#575757" end-socket="left" size="3"}   

[]{.leaderline start="#bad-data-table"  end="#tip3"
    path="straight" 
    start-border-style="color:#575757; x: 0%; y:0%; width:100%; height:100%"
    color="#575757" end-socket="left" size="3"}   

## スライドメッセージを絞り込む: Part 1

[③ スライド作成・資料化]{.topleftbox}

{{< reveal_vspace 2em >}}

::::{#sliide1}

:::{.main-message-block}

ここ10年で売上は19%拡大しているが、営業利益は34%の減少

:::

:::: {.columns}
::: {.column width="70%"}


<div id="compare" style="width: 100%; height: 22.5em;"></div>

<script>

anychart.onDocumentReady(function () {
        // Sample annual sales data from 2010 to 2020
        let rawData = [
          ["2010", 102, 38, 140],
          ["2019", 141, 25, 167]
        ];

        let dataSet = anychart.data.set(rawData);
        let cost_series = dataSet.mapAs({ x: 0, value: 1 });
        let profit_series = dataSet.mapAs({ x: 0, value: 2 });

        // create a column chart instance
        let chart = anychart.column();

        // stack values on y scale.
        chart.yScale().stackMode('value');

        // store series
        let series;
        series = chart.column(cost_series);
        series.id("cost_series");  // Fixed ID for cost series

        setupSeries(series, "費用", "#A9A9A9", "#A9A9A9");
        series.labels()
              .enabled(true)
              .format("{%Value}")  // You can also use "{%y}" for the Y value
              .position("center")  // Optional: "inside", "outside", "center"
              .anchor("center")    // Aligns label within bar
              .fontColor("white") // Good contrast inside a colored bar
              .fontSize(20);
        
        series = chart.column(profit_series);
        series.id("profit_series");  // Fixed ID for profit setupSeries
        
        setupSeries(series, "営業利益", "#0E3666", "#0E3666");
        series.labels()
              .enabled(true)
              .format("{%Value}")  // You can also use "{%y}" for the Y value
              .position("center")  // Optional: "inside", "outside", "center"
              .anchor("center")    // Aligns label within bar
              .fontColor("white") // Good contrast inside a colored bar
              .fontSize(20);

        // Add title and axis labels
        chart.xAxis().title().fontSize(20).fontWeight("bold").fontFamily("Meiryo");
        chart.yAxis().title().fontSize(20).fontWeight("bold").fontFamily("Meiryo");

        chart.pointWidth("40%");
        // chart.xAxis().title("Year");
        chart.xAxis().stroke({ color: "black", thickness: 1 });
        chart.yAxis().stroke({ color: "black", thickness: 1 });
        chart.yAxis().title("Sales (in millions)").padding([0, 0, 10, 0]); // Adding the unit to the 
        // Y-axis title
        // Enable legend
        // label config
        var label_x = chart.xAxis().labels();
        var label_y = chart.yAxis().labels();
        label_x.fontFamily("Meiryo");
        label_y.fontFamily("Meiryo");
        label_x.fontSize(20);
        label_y.fontSize(20);
        label_x.fontColor("#1a1a1a");
        label_y.fontColor("#1a1a1a");

        // title config
        var title = chart.title();
        title.enabled(true);
        title.fontSize(26);
        title.fontColor("#575757");
        title.fontWeight(200);
        title.text("売上と営業利益額の推移(2010 vs 2019年)");
        
        //legend
        chart.legend()
             .enabled(true)
             .fontSize(20)       // Change text size
             .iconSize(20)       // Change icon size
             .padding(10)        // Padding inside legend
             .margin(10);        // Margin around legend
        chart.legend(true);

        // union
        chart.tooltip().displayMode("union");
        chart.tooltip().titleFormat(function(e){
          return this.x + ' - ' + this.points[0].getStat('categoryYSum');
        });


        chart.container("compare");
        chart.draw(); // Finally, draw the chart
});
</script>

:::
::: {.column width="30%"}

{{< reveal_vspace 2.5em >}}

[売上増減率]{.border-bottom style="width: 10em; text-align: center;"}


[\+ 19%]{.message-block style="width: 10em; text-align: center;"}

{{< reveal_vspace 2.2em >}}

[コスト増減率]{.border-bottom style="width: 10em; text-align: center;"}


[\+ 38%]{.message-block style="width: 10em; text-align: center;"}

{{< reveal_vspace 2.2em >}}

[営業利益増減率]{.border-bottom style="width: 10em; text-align: center;"}


[\- 34%]{.message-block style="width: 10em; text-align: center;"}


:::

::::
::::

:::{.message-box style="font-size:0.9em; position: absolute; top: 0%; left: 65%" #focus-message}

- このスライドでは「売上は増えているのに営業利益は減少している」という直感に反した情報を聞き手に理解してもらうことが目的
- 「**直感に反した情報**」はシンプルかつ明快なロジックで説明したほうが良い

:::

## スライドメッセージを絞り込む: Part 2

[③ スライド作成・資料化]{.topleftbox}

{{< reveal_vspace 2em >}}

::::{#sliide1}

:::{.main-message-block}

人件費の大幅な増加が利益率低下の主因であり、売上増分の約8割が人件費の増加によって相殺されている


:::

<div id="anychart-waterfall-container" style="width: 100%; height: 630px;"></div>

<script>
    anychart.onDocumentReady(function () {
        const fontsize = 16;

        const data = [
            {x: '営業利益(2010年)', value: 38 , custom_field: "売上 140"},
            {x: '売上増加', value: 26},
            {x: '原価', value: -7},
            {x: '人件費', value: -20,},
            {x: '広告宣伝費', value: -5},
            {x: 'その他費用', value: -7},
            {x: '営業利益(2019年)', isTotal: true, custom_field: "売上 166"}];

        // create a waterfall chart
        let chart = anychart.waterfall();
        let series = chart.waterfall(data); // returns the series

        series.labels()
              .format("{%Value}")  // You can also use "{%y}" for the Y value
              .fontColor("#1a1a1a") // Good contrast inside a colored bar
              .fontSize(20);

        // axis config
        var yScale = chart.yScale();
        yScale.minimum(0);
        yScale.maximum(70);

        // color config
        series.normal().fill("#000080", 0.8);
        series.normal().fallingFill("#808080", 0.3);
        series.normal().fallingStroke("#808080", 1, "10 5", "round");
        series.normal().risingFill("#1E90FF", 0.3);
        series.normal().risingStroke("#1E90FF", 1, "10 5", "round");

        series.select(3);
        
        chart.xAxis().stroke({ color: "black", thickness: 1 });
        chart.yAxis().stroke({ color: "black", thickness: 1 });

        // label config
        var labels = chart.xAxis().labels();
        labels.fontFamily("Meiryo")
              .fontSize(fontsize)
              .fontColor("#000000")
              .fontSize(20)
              .useHtml(false);
        
        var labels = chart.yAxis().labels();
        labels.fontFamily("Meiryo")
              .fontSize(fontsize)
              .fontColor("#000000")
              .fontSize(16)
              .useHtml(false);

        // title config
        var title = chart.title();
        title.enabled(true);
        title.text("営業利益増減の内訳(2010年 vs 2019年)");
        title.fontSize(28);
        title.fontColor("#575757");
        title.fontWeight(200);
        // title.fontDecoration("underline");
        chart.tooltip().titleFormat("Absolute | Difference");
        chart.tooltip().format("{%absolute}\n{%diff}\n\n{%custom_field}");

        
        chart.container('anychart-waterfall-container');
        chart.draw();;



    });
</script>

::::

:::{.message-box style="font-size:0.8em; position: absolute; top: 0%; left: 60%" #focus-message}

前のスライドの「売上が増加しているのに営業利益が減少した」に対するfollow-up question「**どのコストが特に増加したのか？**」に答えることで論理的にスムーズな流れとなる
:::




# Appendix

## 論文におけるHeadingsとTakeaways

:::: {.columns}
::: {.column style="width: 60%"}

:::::{.keypoints-container style="height: 90%; width: 100%; font-size: 1.1em;"}

::::{.keypoints-block }

:::{.no-border-block}

[[Headings( 見出し )]{#def-headings}]{.block-header}

:::{.checkmark}
- 議論や情報を階層化するためのセクションタイトル
    - [「イントロ」「先行研究」「手法」「結果」「考察」「結論」]{style="font-size:0.9em"}
- Headingsから関心部分にすぐアクセスできる
:::
:::

:::{.no-border-block}

[[Takeaways( 要点 )]{#def-takeaways}]{.block-header}

:::{.checkmark}
- 各セクションの要点や主張を示す
- 通常はHeadingの直後に書かれる(**MMUF**の原則)
    - [全文を読まずに、素早く全体の骨子・要点をつかめる]{style="font-size:0.9em"}

:::
:::

::::
:::::


:::

::: {.column style="width: 40%"}

```{=html}
<div class="research-paper-style">
<h3 id="heading-box1"> 3. Data and Methodology</h3>

<div class="takeaway" id="takeaway-box1">
    We combine satellite imagery with city-level land-use data to model temperature variation.
</div>

<p>
    This section describes the datasets used and the modeling techniques applied to quantify urban heat island effects.
</p>

<h4 id="heading-box2"> 3.1 Data Sources</h4>

<div class="takeaway" id="takeaway-box2">
  We utilized satellite thermal data and open geospatial datasets to quantify urban heat islands, focusing on five major cities and temporal alignment of vegetation indices with land surface temperature.
</div>
<p>
  To conduct a comprehensive analysis of urban heat island (UHI) effects, we assembled a multi-source dataset ...
</p>


</div>
```

:::


[]{.leaderline start="#def-headings"  end="#heading-box1" 
    color="#A9A9A9" end-socket="left" size="3" dash=true 
    end-border-style="color:#1a1a1a; radius:10"
    index="1" lineid="line1"}   

[]{.leaderline start="#def-headings"  end="#heading-box2" color="#A9A9A9"
    end-socket="left" size="3" dash=true  
    path="straight"
    end-border-style="color:#1a1a1a; radius:10"
    index="1" lineid="line2"}   

[]{.leaderline start="#def-takeaways"  end="#takeaway-box1" color="#A9A9A9"
    end-socket="left" size="3" dash=true  
    path="straight"
    end-border-style="color:#1a1a1a; radius:10"
    index="2" lineid="line3"}   
[]{.leaderline start="#def-takeaways"  end="#takeaway-box2" color="#A9A9A9"
    end-socket="left" size="3" dash=true  
    path="straight"
    end-border-style="color:#1a1a1a; radius:10"
    index="2" lineid="line4"}   

::::
