---
title: "データ活用と法的リスク"
subtitle: "法学101"
author: "Ryo Nakagami"
date: "2026-02-17"
categories: [Legal]
slide-number: true
# resources:
#     - sample_data.csv
filters:
  - reveal-auto-agenda
  - regmonkey_slide_editing
auto-agenda:
  bullets: bullets
# chalkboard: false
# embed-resources: true
---

## Yahoo!BB 情報漏洩事件
[個人情報の適切管理義務と不法行為責任 大阪地判H18.5.19]{.h2-submessage .font-10}

:::: {.sidebar .font-08}

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi question-circle size=1.7em color=#428CE6 >}} 

### [論点]{.ml-2}

:::

:::{.padding-L-10}

- 個人情報の適切管理に必要な措置を講じなかったため情報が不正に取得された場合，管理主体は不法行為責任を負うか？
- 関連条文: 民法709条・710条

:::

::::

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi list-ul size=1.7em color=#428CE6 >}} 

### [事実]{.ml-2}

:::

:::{.padding-L-10}

- 電気通信事業を営む $Y_1$（ヤフー株式会社）, $Y_2$（ソフトバンクBB） は共同してインターネット接続サービス等を提供
- $Y_2$ は，社内サーバーに本件サービスにかかる顧客情報を記録していたが，社外からのメンテナンス作業を可能にするため，リモートサーバーを設置
- $Y_2$ の業務委託先から派遣され，顧客サーバーの管理業務に従事していた $A$ は，退職後，リモートアクセスのために付与されていた認証情報を用いて顧客サーバーにアクセスし，不正に顧客情報を取得
- 個人情報（氏名、住所、電話番号など）が流出したことを受け，$Y$ のインターネット接続サービス利用者 $X$ らは， $Y$ が個人情報の適切な管理を怠った過失等により自己情報コントロール権を侵害されたとして，$Y$ らに対して共同不法行為に基づく損害賠償を請求

:::

::::

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi book size=1.7em color=#428CE6 >}} 

### [判旨]{.ml-2}

:::

:::{.padding-L-10}

- ユーザー名とパスワードによる認証以外に外部からのアクセスを規制する措置が取られていない上，肝心のユーザー名とパスワードの管理が極めて不十分，と裁判所は指摘
- 電気通信事業における個人情報保護に関するガイドラインや，個人情報保護法における個人情報の適切な管理に関する規定を踏まえ，裁判所は「外部からの不正アクセスを防止するための相当な措置を講ずべき注意義務を怠った過失」に基づき，BBテクノロジーの不法行為責任を認定
- ヤフーに対する請求は，「ヤフーが直接管理していた情報の流出はなく、賠償責任は負わない」として棄却

:::

::::

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi lightbulb size=1.7em color=#428CE6 >}} 


### [ポイント]{.ml-2}


:::

:::{.padding-L-10}

- 管理主体が負う私法上の注意義務の内容確定に，ガイドラインや個人情報保護法の規定が果たす役割を認めた点で重要
- 個人情報の適切な管理のため必要な措置を講ずべき注意義務を怠った場合，不法行為責任が認められ得るとした点も重要

:::

::::


::::


## 眼科医事件
[電話帳掲載情報を電子掲示板で公開する行為の不法行為責任 神戸地判H11.6.23]{.h2-submessage .font-10}

:::: {.sidebar .font-08}

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi question-circle size=1.7em color=#428CE6 >}} 

### [論点]{.ml-2}

:::

:::{.padding-L-10}

- 電話帳に掲載されている氏名・住所・電話番号を電子掲示板に転載する行為は不法行為（民法709条）となるか？
- 公開情報であっても，インターネット上で再公開することはプライバシー侵害に当たるか？
- 関連条文: 民法709条・710条

:::

::::

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi list-ul size=1.7em color=#428CE6 >}} 

### [事実]{.ml-2}

:::

:::{.padding-L-10}

- 眼科医である $X$（原告）は，電話帳に自己の氏名・住所・電話番号を掲載していた
- 被告 $Y$ は，インターネット接続会社ニフティの電子掲示板上に $X$ の電話帳掲載情報(眼科医の氏名，職業，診療所の住所・電話番号)を記載
- 書き込みが行われた日は34回，翌日には10回，診療所にいたずら電話がかかってきた．さらに，注文していない商品が合計3回，通信販売会社から診療所に配達された
- $X$ は，事故のプライバシー侵害，開業する眼科の診療の妨害，信用を既存されたと主張して， $Y$ に対し不法行為に基づく損害賠償を請求

:::

::::

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi book size=1.7em color=#428CE6 >}} 

### [判旨]{.ml-2}

:::

:::{.padding-L-10}

- 「本件個人情報は，$X$ の業務の内容からして当然に対外的に周知されることが予定されているものといえるから，必ずしも純粋な私生活上の事柄であるとは言い難い」が，その個人情報であっても，正当な目的・方法のもとで利用される限度で公開が予定されているにすぎない
- 個人情報を一定の目的のために公開したものが，それが「目的外に悪用されないために，右個人情報を右公開目的と関係ない範囲まで知られたくないと欲することは」保護されるべき利益であり，プライバシーの権利の基本的属性に含まれる
- 本件個人情報は，公開を一般に欲しないし，診療所を探す者以外の一般人には未だ知られていない事柄であるといえる一方，電子掲示板に転載し，不特定多数が容易に閲覧できる状態に置く行為は，誹謗中傷被害の発生の危険性をもたらす恐れのある行為であることから，$X$ のプライバシーを侵害するものとして不法行為（民法709条）に該当する

:::

::::

{{< reveal_vspace 0.35em >}}

::::{.component-card-index .pl-4 .pr-4 .pt-0 .pb-0 .border-blue-500}

:::{.flex .items-center}
  
{{< bi lightbulb size=1.7em color=#428CE6 >}} 

### [ポイント]{.ml-2}

:::

:::{.padding-L-10}

- 一旦公開された情報であっても，公開の目的・範囲を超えて拡散されない利益は保護されるという，個人情報の伝播範囲の制限を保護されるべき法的利益として認めた判決として重要

:::

::::


::::
