---
title: "pentagon-squared-boxスライド"
subtitle: "revealjsスライド作成紹介"
author: "Ryo Nakagami"
date: "2025-09-21"
categories: [template]
slide-number: true
filters:
  - reveal-auto-agenda
  - inject_anychart_js
  - regmonkey_slide_editing
auto-agenda:
  bullets: bullets
# chalkboard: false
# embed-resources: true
---

## pentagon-squared-boxスライド例 with `.pentagon-box-500` 

{{< reveal_vspace 0.5em >}}

:::: {.info-box style="font-size:1.1em;"}

[Conversational Data Analysis(会話型データ分析)]{.info-box-title}

::: {.info-contents style="padding-left:1em"}

- データ分析フロー全体において，DSメンバー同士のコミュニケーションを重視して分析を進めるスタイル
- 仮説生成から検証・洞察共有まで，メンバー同士が自然に対話できる場を重視
- 分析の試行錯誤をコラボレーションとして加速し，知識の再利用性を高めることを目指す

:::
::::

{{< reveal_vspace 1em >}}

<!-- pentagon-squared-box style -->

:::::: {.columns}
::::: {.column width="50%"}

<!-- left pentagon-box -->

::::{.pentagon-box-500}

:::{.border-bottom-header-left}

データ分析プロジェクトにおける課題

:::

:::{.squaredmark style="font-size: 0.9em"}

- データ分析の方針・手法・解釈が分析担当者個人に依存
  - 再現性・継続性が低下し，分析の属人的ミスの発生

{{< reveal_vspace 0.5em >}}

- データ分析プロセスが終わった段階で分析が共有されがち
  - チーム全体の知見を分析方針策定に結び付けられない
  - FBが遅れ，軌道修正が難しい

{{< reveal_vspace 0.5em >}}

- プロジェクトメンバー内部での情報共有が遅延
  - 新規アサインメンバーのオンボがスムーズに進まない

:::

::::
:::::

::::: {.column width="50%"}

<!-- right squared-box -->

::::{ .square-box-500}

:::{.border-bottom-header-left}

会話型データ分析の実現ステップ

:::


:::{.squaredmark style="font-size: 0.9em"}

- Step 1: RAP[^footer1] の観点で現状の知見を整理する
- Step 2: 現状課題の洗い出し，言語化
  - 分析視点に偏りがないか確かめる
- Step 3: 仮説や分析アプローチをワークショップなどで議論
- Step 4: ロードマップ合意
  - アドバイスを踏まえ，いつまでにどこまでの分析を実施するのかチームメンバーでスモールに合意
- Step 5: 分析の実行

:::

::::
:::::
::::::

[^footer1]: Research Question, Answer, Positioningの整理フレームワーク

## `.pentagon-box-550` テンプレート

{{< reveal_vspace 0.5em >}}

<!-- pentagon-squared-box style -->

:::::: {.columns}
::::: {.column width="50%"}

<!-- left pentagon-box -->

::::{.pentagon-box-550}

:::{.border-bottom-header-left}

データ分析プロジェクトにおける課題

:::

:::{.squaredmark style="font-size: 0.9em"}

- データ分析の方針・手法・解釈が分析担当者個人に依存
  - 再現性・継続性が低下し，分析の属人的ミスの発生

{{< reveal_vspace 0.5em >}}

- データ分析プロセスが終わった段階で分析が共有されがち
  - チーム全体の知見を分析方針策定に結び付けられない
  - FBが遅れ，軌道修正が難しい

{{< reveal_vspace 0.5em >}}

- プロジェクトメンバー内部での情報共有が遅延
  - 新規アサインメンバーのオンボがスムーズに進まない

:::

::::
:::::

::::: {.column width="50%"}

<!-- right squared-box -->

::::{ .square-box-550}

:::{.border-bottom-header-left}

会話型データ分析の実現ステップ

:::


:::{.squaredmark style="font-size: 0.9em"}

- Step 1: RAP[^footer1] の観点で現状の知見を整理する
- Step 2: 現状課題の洗い出し，言語化
  - 分析視点に偏りがないか確かめる
- Step 3: 仮説や分析アプローチをワークショップなどで議論
- Step 4: ロードマップ合意
  - アドバイスを踏まえ，いつまでにどこまでの分析を実施するのかチームメンバーでスモールに合意
- Step 5: 分析の実行

:::

::::
:::::
::::::

[^footer1]: Research Question, Answer, Positioningの整理フレームワーク




## `.pentagon-box-600` テンプレート

{{< reveal_vspace 0.5em >}}

<!-- pentagon-squared-box style -->

:::::: {.columns}
::::: {.column width="50%"}

<!-- left pentagon-box -->

::::{.pentagon-box-600}

:::{.border-bottom-header-left}

データ分析プロジェクトにおける課題

:::

:::{.squaredmark style="font-size: 0.9em"}

- データ分析の方針・手法・解釈が分析担当者個人に依存
  - 再現性・継続性が低下し，分析の属人的ミスの発生

{{< reveal_vspace 0.5em >}}

- データ分析プロセスが終わった段階で分析が共有されがち
  - チーム全体の知見を分析方針策定に結び付けられない
  - FBが遅れ，軌道修正が難しい

{{< reveal_vspace 0.5em >}}

- プロジェクトメンバー内部での情報共有が遅延
  - 新規アサインメンバーのオンボがスムーズに進まない

:::

::::
:::::

::::: {.column width="50%"}

<!-- right squared-box -->

::::{ .square-box-600}

:::{.border-bottom-header-left}

会話型データ分析の実現ステップ

:::


:::{.squaredmark style="font-size: 0.9em"}

- Step 1: RAP[^footer1] の観点で現状の知見を整理する
- Step 2: 現状課題の洗い出し，言語化
  - 分析視点に偏りがないか確かめる
- Step 3: 仮説や分析アプローチをワークショップなどで議論
- Step 4: ロードマップ合意
  - アドバイスを踏まえ，いつまでにどこまでの分析を実施するのかチームメンバーでスモールに合意
- Step 5: 分析の実行

:::

::::
:::::
::::::

[^footer1]: Research Question, Answer, Positioningの整理フレームワーク



## `.pentagon-box-700` テンプレート

{{< reveal_vspace 0.5em >}}

<!-- pentagon-squared-box style -->

:::::: {.columns}
::::: {.column width="50%"}

<!-- left pentagon-box -->

::::{.pentagon-box-700}

:::{.border-bottom-header-left}

データ分析プロジェクトにおける課題

:::

:::{.squaredmark style="font-size: 0.9em"}

- データ分析の方針・手法・解釈が分析担当者個人に依存
  - 再現性・継続性が低下し，分析の属人的ミスの発生

{{< reveal_vspace 0.5em >}}

- データ分析プロセスが終わった段階で分析が共有されがち
  - チーム全体の知見を分析方針策定に結び付けられない
  - FBが遅れ，軌道修正が難しい

{{< reveal_vspace 0.5em >}}

- プロジェクトメンバー内部での情報共有が遅延
  - 新規アサインメンバーのオンボがスムーズに進まない

:::

::::
:::::

::::: {.column width="50%"}

<!-- right squared-box -->

::::{ .square-box-700}

:::{.border-bottom-header-left}

会話型データ分析の実現ステップ

:::


:::{.squaredmark style="font-size: 0.9em"}

- Step 1: RAP[^footer1] の観点で現状の知見を整理する
- Step 2: 現状課題の洗い出し，言語化
  - 分析視点に偏りがないか確かめる
- Step 3: 仮説や分析アプローチをワークショップなどで議論
- Step 4: ロードマップ合意
  - アドバイスを踏まえ，いつまでにどこまでの分析を実施するのかチームメンバーでスモールに合意
- Step 5: 分析の実行

:::

::::
:::::
::::::

[^footer1]: Research Question, Answer, Positioningの整理フレームワーク
